
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('books').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('books').insert({id:1, title: 'Alaska: A Novel', author: 'James A. Michener', description: 'In this sweeping epic of the northernmost American frontier, James A. Michener guides us through Alaska’s fierce terrain and history, from the long-forgotten past to the bustling present. As his characters struggle for survival, Michener weaves together the exciting high points of Alaska’s story: its brutal origins; the American acquisition; the gold rush; the tremendous growth and exploitation of the salmon industry; the arduous construction of the Alcan Highway, undertaken to defend the territory during World War II. A spellbinding portrait of a human community fighting to establish its place in the world, Alaska traces a bold and majestic saga of the enduring spirit of a land and its people.', image: 'https://images-na.ssl-images-amazon.com/images/I/51QAlv66fEL.jpg', listed:0}),
        knex('books').insert({id:2, title: 'Fantastic Beasts and Where to Find Them: The Original Screenplay ', author: 'J.K. Rowling', description: 'J.K. Rowling\'s screenwriting debut is captured in this exciting hardcover edition of the Fantastic Beasts and Where to Find Them screenplay.When Magizoologist Newt Scamander arrives in New York, he intends his stay to be just a brief stopover. However, when his magical case is misplaced and some of Newt\'s fantastic beasts escape, it spells trouble for everyone…', image: 'https://images-na.ssl-images-amazon.com/images/I/61kS08bR-EL._SX311_BO1,204,203,200_.jpg', listed:0}),
        knex('books').insert({id:3, title: 'Sisters One, Two, Three', author: 'Nancy Star', description: 'After a tragic accident on Martha’s Vineyard, keeping secrets becomes a way of life for the Tangle family. With memories locked away, the sisters take divergent paths. Callie disappears, Mimi keeps so busy she has no time to think, and Ginger develops a lifelong aversion to risk that threatens the relationships she holds most dear. When a whispered comment overheard by her rebellious teenage daughter forces Ginger to reveal a long-held family secret, the Tangles’ carefully constructed web of lies begins to unravel. Upon the death of Glory, the family’s colorful matriarch, and the return of long-estranged Callie, Ginger resolves to return to Martha’s Vineyard and piece together what really happened on that calamitous day when a shadow fell over four sun-kissed siblings playing at the shore. Along with Ginger’s newfound understanding come the keys to reconciliation: with her mother, with her sisters, and with her daughter.', image: 'https://images-na.ssl-images-amazon.com/images/I/515TZItXNeL.jpg', listed:0})
      ]);
    });
};
